### ISSUE TITLE
Ctrl-C and Ctrl-D do not work

### ISSUE THREAD

**Issue by komh** [komh/mksh-os2#1]
Ctrl-C should stop the current command input and start new command input.

Ctrl-D should quit mksh. However, it does not on vi mode.(set -o vi).

**Comment by mirabilos** [comment]
Look at edchars.intr and edchars.quit in edit.c – maybe that helps.

**Comment by komh** [comment]
Ooops... I should have read this comment before fixing this issue myself. If that, I could reduce the time it took to fix this issue.

Fixed by commit edc36cce7f8d8ae2ea4d67ee722c8657d8dd6ee7.
